import type { Product } from "@/types/product";

// ─── 7 feature products (mapped 1:1 to Midjourney images) + 3 essentials ───
// Prices deliberately varied to feel commercial, not synthetic.

export const sampleProducts: Product[] = [
  {
    id: "1",
    nameEn: "Burgundy Rose Ivory Silk",
    nameAr: "حرير عاجي بورد عنابي",
    slug: "burgundy-rose-ivory-silk",
    descriptionEn:
      "Heirloom ivory silk charmeuse, hand-embroidered with cascading burgundy roses and antique gold vines. A statement cloth that carries its own presence into the room — unrepeatable, made in a 28-piece run.",
    descriptionAr:
      "حرير شارميوز عاجي موروث، مطرز يدوياً بورود عنابية متدفقة وكرمات ذهبية عتيقة. قماش مميز يحمل حضوره الخاص إلى الغرفة — فريد من نوعه، من إنتاج محدود 28 قطعة.",
    pricePerMeter: 720,
    compareAtPrice: 860,
    minOrderMeters: 2,
    sku: "LF-BRI-001",
    fabricType: "silk",
    fabricWeight: "140 GSM",
    fabricWidth: "140 cm",
    composition: "100% Mulberry Silk · Hand-embroidered bullion & silk floss",
    careInstructions: "Dry clean only. Store flat, away from direct light.",
    origin: "Embroidered in Dubai",
    certifications: ["OEKO-TEX Standard 100"],
    isCustomizable: true,
    isFeatured: true,
    isLimited: true,
    inStock: true,
    stockQuantity: 18,
    collection: "bridal",
    colorFamily: "burgundy",
    styledWith: ["3", "5", "9"],
    images: [
      { id: "img-1-a", url: "/images/products/kaftan-burgundy-rose.png", sortOrder: 0, isMain: true, alt: "Burgundy rose ivory silk kaftan" },
    ],
    variants: [],
    tags: ["silk", "embroidered", "ivory", "burgundy", "gold", "bridal", "limited"],
    createdAt: "2025-09-01",
    updatedAt: "2026-03-15",
  },
  {
    id: "2",
    nameEn: "Champagne Royal Chiffon",
    nameAr: "شيفون شامبين ملكي",
    slug: "champagne-royal-chiffon",
    descriptionEn:
      "All-over champagne chiffon worked with gold metallic thread, pearl beads, and silver sequins. Soft drape that catches candlelight across a room. Designed for Eid, engagement, and celebration.",
    descriptionAr:
      "شيفون شامبين مطرز بالكامل بخيوط ذهبية معدنية، خرز لؤلؤ، وترتر فضي. انسدال ناعم يلتقط ضوء الشموع عبر الغرفة. مصمم للعيد، الخطوبة، والاحتفالات.",
    pricePerMeter: 560,
    minOrderMeters: 2,
    sku: "LF-CRC-002",
    fabricType: "chiffon",
    fabricWeight: "85 GSM",
    fabricWidth: "145 cm",
    composition: "Silk chiffon · Metallic bullion · Seed pearls · Sequin",
    careInstructions: "Dry clean only.",
    origin: "Embroidered in Dubai",
    isCustomizable: true,
    isFeatured: true,
    isNew: true,
    inStock: true,
    stockQuantity: 34,
    collection: "occasion",
    colorFamily: "gold",
    styledWith: ["5", "6", "1"],
    images: [
      { id: "img-2-a", url: "/images/products/kaftan-champagne-royal.png", sortOrder: 0, isMain: true, alt: "Champagne royal chiffon kaftan" },
    ],
    variants: [],
    tags: ["chiffon", "champagne", "gold", "pearl", "occasion", "new"],
    createdAt: "2026-02-10",
    updatedAt: "2026-04-01",
  },
  {
    id: "3",
    nameEn: "Pearl & Gold Chiffon",
    nameAr: "شيفون لؤلؤي وذهبي",
    slug: "pearl-and-gold-chiffon",
    descriptionEn:
      "Ivory chiffon with a dense V-neck medallion of seed pearls, bullion scrollwork, and silver thread. Cascading borders at hem and cuff. Bridal fabric designed to photograph.",
    descriptionAr:
      "شيفون عاجي مع ميدالية كثيفة برقبة V من خرز اللؤلؤ، تطريز معدني، وخيط فضي. حواف متدفقة عند الذيل والكم. قماش زفاف مصمم للتصوير.",
    pricePerMeter: 640,
    minOrderMeters: 2,
    sku: "LF-PGC-003",
    fabricType: "chiffon",
    fabricWeight: "90 GSM",
    fabricWidth: "150 cm",
    composition: "Silk chiffon · Seed pearl · Silver & gold bullion",
    careInstructions: "Dry clean only. Handle with care.",
    origin: "Embroidered in Dubai",
    certifications: ["OEKO-TEX Standard 100"],
    isCustomizable: true,
    isFeatured: true,
    inStock: true,
    stockQuantity: 22,
    collection: "bridal",
    colorFamily: "cream",
    styledWith: ["1", "6", "8"],
    images: [
      { id: "img-3-a", url: "/images/products/kaftan-pearl-gold.png", sortOrder: 0, isMain: true, alt: "Pearl and gold chiffon kaftan" },
    ],
    variants: [],
    tags: ["chiffon", "pearl", "gold", "ivory", "bridal"],
    createdAt: "2025-11-15",
    updatedAt: "2026-03-20",
  },
  {
    id: "4",
    nameEn: "Peach Blossom Silk",
    nameAr: "حرير زهر الخوخ",
    slug: "peach-blossom-silk",
    descriptionEn:
      "Ivory silk scattered with embroidered peach blossoms and muted gold leaves. Soft enough for drape, substantial enough to hold shape — our most-ordered bridal fabric.",
    descriptionAr:
      "حرير عاجي متناثر بزهور الخوخ المطرزة وأوراق ذهبية هادئة. ناعم بما يكفي للانسدال، ومميز بما يكفي للحفاظ على الشكل — أكثر أقمشة الزفاف طلباً لدينا.",
    pricePerMeter: 490,
    minOrderMeters: 2,
    sku: "LF-PBS-004",
    fabricType: "silk",
    fabricWeight: "120 GSM",
    fabricWidth: "150 cm",
    composition: "100% Pure Silk · Silk floss embroidery",
    careInstructions: "Dry clean only.",
    origin: "Embroidered in Dubai",
    isCustomizable: true,
    isFeatured: true,
    inStock: true,
    stockQuantity: 52,
    collection: "bridal",
    colorFamily: "cream",
    styledWith: ["3", "1", "7"],
    images: [
      { id: "img-4-a", url: "/images/products/kaftan-peach-blossom.png", sortOrder: 0, isMain: true, alt: "Peach blossom ivory silk kaftan" },
    ],
    variants: [],
    tags: ["silk", "embroidered", "peach", "gold", "bridal"],
    createdAt: "2024-06-01",
    updatedAt: "2026-03-01",
  },
  {
    id: "5",
    nameEn: "Golden Heritage Kaftan Silk",
    nameAr: "حرير ذهبي تراثي",
    slug: "golden-heritage-kaftan-silk",
    descriptionEn:
      "Warm ivory silk with traditional Khaleeji panels rendered in antique gold. Heritage pattern, lightweight drape, designed for everyday wearing into heirloom territory.",
    descriptionAr:
      "حرير عاجي دافئ مع لوحات خليجية تقليدية بالذهب العتيق. نمط تراثي، انسدال خفيف الوزن، مصمم للارتداء اليومي ليصبح إرثاً.",
    pricePerMeter: 420,
    minOrderMeters: 2,
    sku: "LF-GHK-005",
    fabricType: "silk",
    fabricWeight: "110 GSM",
    fabricWidth: "145 cm",
    composition: "Silk blend · Gold metallic thread",
    careInstructions: "Dry clean only.",
    origin: "Embroidered in Dubai",
    isCustomizable: true,
    isFeatured: true,
    inStock: true,
    stockQuantity: 41,
    collection: "occasion",
    colorFamily: "gold",
    styledWith: ["2", "6", "4"],
    images: [
      { id: "img-5-a", url: "/images/products/kaftan-golden-heritage.png", sortOrder: 0, isMain: true, alt: "Golden heritage kaftan silk" },
    ],
    variants: [],
    tags: ["silk", "gold", "heritage", "khaleeji", "occasion"],
    createdAt: "2025-08-20",
    updatedAt: "2026-02-20",
  },
  {
    id: "6",
    nameEn: "White Gold Floral Net",
    nameAr: "شبك زهري أبيض ذهبي",
    slug: "white-gold-floral-net",
    descriptionEn:
      "Fine tulle net scattered with hand-embroidered gold botanicals. Best layered over solid silk. A versatile bridal base used across our custom commissions.",
    descriptionAr:
      "شبك تول ناعم متناثر بنباتات ذهبية مطرزة يدوياً. يفضل ارتداؤه فوق حرير سادة. قاعدة زفاف متعددة الاستخدامات نستخدمها في تصاميمنا المخصصة.",
    pricePerMeter: 380,
    minOrderMeters: 2,
    sku: "LF-WGF-006",
    fabricType: "tulle",
    fabricWeight: "60 GSM",
    fabricWidth: "150 cm",
    composition: "Tulle net · Gold bullion embroidery",
    careInstructions: "Dry clean recommended.",
    origin: "Embroidered in Dubai",
    isCustomizable: true,
    isFeatured: true,
    inStock: true,
    stockQuantity: 46,
    collection: "bridal",
    colorFamily: "cream",
    styledWith: ["3", "2", "5"],
    images: [
      { id: "img-6-a", url: "/images/products/kaftan-white-gold-floral.png", sortOrder: 0, isMain: true, alt: "White gold floral net kaftan" },
    ],
    variants: [],
    tags: ["tulle", "net", "white", "gold", "bridal", "floral"],
    createdAt: "2024-11-01",
    updatedAt: "2026-02-15",
  },
  {
    id: "7",
    nameEn: "Blush Pink Crystal Organza",
    nameAr: "أورجانزا كريستال وردي",
    slug: "blush-pink-crystal-organza",
    descriptionEn:
      "Pale blush organza detailed with crystal seed beads and iridescent sequin clusters. Wing-sleeve drape. The softest expression of our Pink Salt palette.",
    descriptionAr:
      "أورجانزا وردية فاتحة مزينة بخرز كريستال صغير وعناقيد ترتر متلألئة. انسدال أكمام واسعة. أنعم تعبير عن لوحة الوردي الملحي لدينا.",
    pricePerMeter: 545,
    compareAtPrice: 620,
    minOrderMeters: 2,
    sku: "LF-BPC-007",
    fabricType: "organza",
    fabricWeight: "70 GSM",
    fabricWidth: "150 cm",
    composition: "Silk organza · Crystal seed bead · Sequin",
    careInstructions: "Dry clean only. Handle with care.",
    origin: "Embroidered in Dubai",
    isCustomizable: false,
    isFeatured: true,
    isNew: true,
    inStock: true,
    stockQuantity: 28,
    collection: "occasion",
    colorFamily: "pink",
    styledWith: ["4", "3", "1"],
    images: [
      { id: "img-7-a", url: "/images/products/kaftan-blush-pink-crystal.png", sortOrder: 0, isMain: true, alt: "Blush pink crystal organza kaftan" },
    ],
    variants: [],
    tags: ["organza", "pink", "crystal", "blush", "occasion", "new"],
    createdAt: "2026-01-20",
    updatedAt: "2026-04-10",
  },
  // ─── Essentials (solid-dyed, entry tier) ───
  {
    id: "8",
    nameEn: "Signature Silk Crêpe",
    nameAr: "كريب حرير كلاسيكي",
    slug: "signature-silk-crepe",
    descriptionEn:
      "Solid-dyed pure silk crêpe, woven in Como. Our core base cloth for bespoke commissions — takes embroidery, dye, and cut cleanly. Available in six house tones.",
    descriptionAr:
      "كريب حرير سادة مصبوغ، منسوج في كومو. قماشنا الأساسي للطلبات المخصصة — يقبل التطريز، الصبغ، والقص بدقة. متوفر بستة درجات من الألوان.",
    pricePerMeter: 240,
    minOrderMeters: 3,
    sku: "LF-SSC-008",
    fabricType: "silk",
    fabricWeight: "110 GSM",
    fabricWidth: "140 cm",
    composition: "100% Silk crêpe",
    careInstructions: "Dry clean.",
    origin: "Woven in Como, Italy",
    certifications: ["OEKO-TEX Standard 100"],
    isCustomizable: true,
    isFeatured: false,
    inStock: true,
    stockQuantity: 120,
    collection: "essentials",
    colorFamily: "cream",
    styledWith: ["9", "10", "6"],
    images: [
      { id: "img-8-a", url: "/images/products/kaftan-peach-blossom.png", sortOrder: 0, isMain: true, alt: "Signature silk crepe (essentials)" },
    ],
    variants: [],
    tags: ["silk", "solid", "essentials", "base", "bespoke"],
    createdAt: "2024-03-10",
    updatedAt: "2026-01-10",
  },
  {
    id: "9",
    nameEn: "Pink Salt Cotton-Silk",
    nameAr: "قطن حرير وردي ملحي",
    slug: "pink-salt-cotton-silk",
    descriptionEn:
      "A quiet cotton-silk blend in our house Pink Salt. Cool-to-the-touch, breathable, and substantial — for abayas and unlined summer pieces.",
    descriptionAr:
      "مزيج هادئ من القطن والحرير بلون الوردي الملحي الخاص بنا. بارد الملمس، قابل للتنفس، ومتين — للعبايات والقطع الصيفية غير المبطنة.",
    pricePerMeter: 195,
    minOrderMeters: 5,
    sku: "LF-PSC-009",
    fabricType: "cotton",
    fabricWeight: "95 GSM",
    fabricWidth: "150 cm",
    composition: "60% Egyptian cotton · 40% silk",
    careInstructions: "Hand wash cold. Lay flat to dry.",
    origin: "Woven in Cairo",
    certifications: ["GOTS"],
    isCustomizable: false,
    isFeatured: false,
    isNew: true,
    inStock: true,
    stockQuantity: 88,
    collection: "essentials",
    colorFamily: "pink",
    styledWith: ["8", "10", "7"],
    images: [
      { id: "img-9-a", url: "/images/products/kaftan-blush-pink-crystal.png", sortOrder: 0, isMain: true, alt: "Pink salt cotton-silk blend (essentials)" },
    ],
    variants: [],
    tags: ["cotton", "silk-blend", "pink", "essentials", "everyday", "new"],
    createdAt: "2026-02-01",
    updatedAt: "2026-04-01",
  },
  {
    id: "10",
    nameEn: "Espresso Linen",
    nameAr: "كتان إسبريسو",
    slug: "espresso-linen",
    descriptionEn:
      "Belgian linen dyed in deep espresso. Slub texture, hefty hand, falls in clean architectural folds — for structured abayas and heirloom table linens.",
    descriptionAr:
      "كتان بلجيكي مصبوغ بلون الإسبريسو العميق. ملمس غير منتظم، قبضة قوية، يتدلى في طيات معمارية نظيفة — للعبايات المهيكلة وأقمشة المائدة الموروثة.",
    pricePerMeter: 180,
    minOrderMeters: 5,
    sku: "LF-EL-010",
    fabricType: "linen",
    fabricWeight: "200 GSM",
    fabricWidth: "150 cm",
    composition: "100% Belgian linen",
    careInstructions: "Machine wash cold. Line dry.",
    origin: "Woven in Belgium",
    certifications: ["European Flax"],
    isCustomizable: false,
    isFeatured: false,
    inStock: true,
    stockQuantity: 64,
    collection: "essentials",
    colorFamily: "neutral",
    styledWith: ["8", "9"],
    images: [
      { id: "img-10-a", url: "/images/products/kaftan-burgundy-rose.png", sortOrder: 0, isMain: true, alt: "Espresso linen (essentials)" },
    ],
    variants: [],
    tags: ["linen", "solid", "neutral", "espresso", "essentials", "everyday"],
    createdAt: "2024-05-20",
    updatedAt: "2025-12-10",
  },
];

export function getProductBySlug(slug: string) {
  return sampleProducts.find((p) => p.slug === slug);
}

export function getProductsByCollection(collection: string) {
  return sampleProducts.filter((p) => p.collection === collection);
}

export function getStyledWith(productId: string, limit = 3) {
  const product = sampleProducts.find((p) => p.id === productId);
  if (!product?.styledWith) return [];
  return product.styledWith
    .map((id) => sampleProducts.find((p) => p.id === id))
    .filter((p): p is Product => Boolean(p))
    .slice(0, limit);
}
